import Head from "next/head";
import type { NextPage, InferGetServerSidePropsType } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>userindex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      userindex
    </div>
  );
};

export default Home;
