import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (context) => {
  // const res = await fetch(`https://...`)
  // const data = await res.json()
  const { req, res, query, params } = context;
  console.info({query, params})

  // req: IncomingMessage & {
  //   cookies: NextApiRequestCookies
  // }
  // res: ServerResponse
  // params?: Q
  // query: ParsedUrlQuery
  // const 

  return {
    props: {}, // will be passed to the page component as props
  }
}

const UserWrites: NextPage = () => {
  const router = useRouter();
  const { ...q } = router.query;
  console.log({q})

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>UserWrites</p>
    </div>
  );
};

export default UserWrites;
