import type { NextPage } from 'next'
import Head from 'next/head'

const UserWrites: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>UserWrites</p>
    </div>
    )
}

export default UserWrites 
