import type { NextPage } from "next";
import Head from "next/head";

const Posts: NextPage = () => {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Posts</div>
    </>
  );
};

export default Posts;
