import type { NextPage } from "next";
import { InferGetStaticPropsType } from 'next'
import Head from "next/head";
import { GetStaticProps } from 'next'

type Post = {
    author: string
    title: string
  }
  
  export const getStaticProps: GetStaticProps = async () => {
    //     const res = await fetch('http://localhost:3000/api/posts')
    // const posts: Post[] = await res.json()
  
    return {
      props: {
        posts: [],
      },
    }
  }
  
function PostsIndex({posts}:InferGetStaticPropsType<typeof getStaticProps>) {
    return (
        <>
          <Head>
            <title>Posts</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div>Posts Index</div>
          <ul>
          {posts.map((post: Post, index: number) => (
            <li key={index}>{post.title}</li>
          ))}
        </ul>
        </>
      );
}

// const PostsIndex: NextPage<{posts: any}> = ({posts}) => {
//   return (
//     <>
//       <Head>
//         <title>Posts</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div>Posts Index</div>
//       <ul>
//       {posts.map((post: any, index: number) => (
//         <li key={index}>{post.title}</li>
//       ))}
//     </ul>
//     </>
//   );
// };

// export async function getStaticProps() {
//     // Call an external API endpoint to get posts
//     const res = await fetch('http://localhost:3000/api/posts')
//     const posts = await res.json()
  
//     // By returning { props: { posts } }, the Blog component
//     // will receive `posts` as a prop at build time
//     return {
//       props: {
//         posts,
//       },
//     }
//   }
  

export default PostsIndex;
