import type { NextPage, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { GetServerSideProps } from "next";

type Data = any;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("/api/hello");
  const data: Data = await res.json();

  return {
    props: {
      data,
    },
  };
  // ...
};

function About({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>about</main>
    </>
  );
}

export default About;
