import type { NextPage, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { GetServerSideProps } from "next";
import axios from "axios";

import LoginForm from "../components/LoginForm";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { req, res, query, params } = context;
  let stillInLogin = false;
  try {
    const apiRes = await axios.get("http://127.0.0.1:7777/api/login/check", {
      headers: {
        ...(req.headers as any),
        // ...req.cookies,
      },
    });
    stillInLogin = apiRes.data?.check === true;
  } catch (error) {
  } finally {
  }
  if (stillInLogin) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {}, // will be passed to the page component as props
  };
};

function Login({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm></LoginForm>
    </>
  );
}

export default Login;
